// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';

export function All():Promise<storage.AppSetting>;

export function Update(arg1:storage.AppSetting):Promise<storage.AppSetting>;
