// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Read() {
  return window['go']['storage']['AppSettingManager']['Read']();
}

export function Update(arg1) {
  return window['go']['storage']['AppSettingManager']['Update'](arg1);
}
