// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';

export function Add(arg1:storage.DriverGroup):Promise<string>;

export function All():Promise<Array<storage.DriverGroup>>;

export function Get(arg1:string):Promise<storage.DriverGroup>;

export function IndexOf(arg1:string):Promise<number>;

export function MoveBehind(arg1:string,arg2:number):Promise<Array<storage.DriverGroup>>;

export function Remove(arg1:string):Promise<void>;

export function Update(arg1:storage.DriverGroup):Promise<storage.DriverGroup>;
