// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['storage']['DriverGroupStorage']['Add'](arg1);
}

export function All() {
  return window['go']['storage']['DriverGroupStorage']['All']();
}

export function Get(arg1) {
  return window['go']['storage']['DriverGroupStorage']['Get'](arg1);
}

export function IndexOf(arg1) {
  return window['go']['storage']['DriverGroupStorage']['IndexOf'](arg1);
}

export function MoveBehind(arg1, arg2) {
  return window['go']['storage']['DriverGroupStorage']['MoveBehind'](arg1, arg2);
}

export function Remove(arg1) {
  return window['go']['storage']['DriverGroupStorage']['Remove'](arg1);
}

export function Update(arg1) {
  return window['go']['storage']['DriverGroupStorage']['Update'](arg1);
}
